=== vitessce/vitessce/src/schemas/cell-sets-tabular.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://github.com/vitessce/vitessce/#cell-sets-tabular",
    "title": "Vitessce cell sets data, tabular format",
    "definitions": {
        "colorArray": {
            "type": "array",
            "items": { "type": "integer", "minimum": 0, "maximum": 255 },
            "minItems": 3,
            "maxItems": 3
        }
    },
    "type": "array",
    "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["groupName", "setName", "obsId"],
        "properties": {
            "groupName": { "type": "string" },
            "setName": { "type": "string" },
            "setColor": { "$ref": "#/definitions/colorArray" },
            "obsId": { "type": "string" },
            "predictionScore": {
                "oneOf": [
                    {
                        "type": "number",
                        "minimum": 0.0,
                        "maximum": 1.0
                    },
                    {
                        "type": "null"
                    }
                ]
            }
        }
    }
}

=== vitessce/vitessce/src/schemas/fixtures/obsSetsTabular.good.json
[
    {
        "groupName": "Clustering Algorithm",
        "setName": "Cluster A",
        "setColor": [255, 0, 0],
        "obsId": "cell_243"
    },
    {
        "groupName": "Clustering Algorithm",
        "setName": "Cluster A",
        "setColor": [255, 0, 0],
        "obsId": "cell_271"
    },
    {
        "groupName": "Clustering Algorithm",
        "setName": "Cluster A",
        "setColor": [255, 0, 0],
        "obsId": "cell_247"
    },
    {
        "groupName": "Clustering Algorithm",
        "setName": "Cluster A",
        "setColor": [255, 0, 0],
        "obsId": "cell_248"
    }
]
